# Generated by Django 4.2.7 on 2023-11-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yourmodel',
            old_name='field2',
            new_name='Text',
        ),
        migrations.RenameField(
            model_name='yourmodel',
            old_name='field1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='yourmodel',
            old_name='field3',
            new_name='price',
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='image_field',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
