# Generated by Django 4.2.7 on 2023-11-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0002_rename_field2_yourmodel_text_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourModel',
            new_name='Product',
        ),
    ]
